### ISSUE TITLE
宋老师最近变懒了

### ISSUE THREAD

**Issue by huanghugo** [squirrel20/stl#1]
你好！

因公司业务调整，非常遗憾的向大家宣布多说项目即将关闭。

我们将于2017年6月1日正式关停服务，在此之前您可以通过后台的数据导出功能导出自己站点的评论数据。

对此给您造成的不便，我们深表歉意，感谢您的一路相伴。

**Comment by squirrel20** [comment]
一天各种需求，忙成狗了，压根没时间充电。。。

**Comment by huanghugo** [comment]
❤️，最近在搞什么？

**Comment by squirrel20** [comment]
上班哦，各种需求

**Comment by huanghugo** [comment]
哦哦
